using System;
using System.Threading.Tasks;
using Newtonsoft.Json;

// REUSE-IgnoreStart
namespace TdLib
{
    /// <summary>
    /// Autogenerated TDLib APIs
    /// </summary>
    public static partial class TdApi
    {
        /// <summary>
        /// Returns information about a gift received or sent by the current user
        /// </summary>
        public class GetUserGift : Function<UserGift>
        {
            /// <summary>
            /// Data type for serialization
            /// </summary>
            [JsonProperty("@type")]
            public override string DataType { get; set; } = "getUserGift";

            /// <summary>
            /// Extra data attached to the function
            /// </summary>
            [JsonProperty("@extra")]
            public override string Extra { get; set; }

            /// <summary>
            /// Identifier of the message with the gift
            /// </summary>
            [JsonConverter(typeof(Converter))]
            [JsonProperty("message_id")]
            public long MessageId { get; set; }
        }

        /// <summary>
        /// Returns information about a gift received or sent by the current user
        /// </summary>
        public static Task<UserGift> GetUserGiftAsync(
            this Client client, long messageId = default)
        {
            return client.ExecuteAsync(new GetUserGift
            {
                MessageId = messageId
            });
        }
    }
}
// REUSE-IgnoreEnd